#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
feh --bg-fill Images/background.jpg &

bspc monitor -d I II III IV

bspc config border_width         2
bspc config window_gap          12

bspc config normal_border_color "#0A1F32"
bpsc config active_border_color "#2D384A"
bpsc config focused_border_color "#344756"

bspc config focus_follows_pointer true
bspc config pointer_modifier super

bspc config split_ratio          0.52

bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Правила для окон
bspc rule -a Nemo state=floating
